import Header from "@/components/Header";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [selectedTheme, setSelectedTheme] = useState(
    localStorage.getItem("selectedTheme") || "light"
  );

  const themes = [
    "light",
    "dark",
    "synthwave",
    "dracula",
    "halloween",
    "coffee",
    "aqua",
    "luxury",
    "retro",
    "valentine",
    "night",
    "forest",
    "business",
    "black",
    "cyberpunk",
    "garden",
    "cupcake",
    "bumblebee",
    "lofi",
    "emerald",
    "corporate",
    "pastel",
    "fantasy",
    "wireframe",
    "cmyk",
    "autumn",
    "acid",
    "lemonade",
    "winter",
  ];

  return (
    <>
      <Head>
        <title>airbnb 2.0</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <div className="min-h-screen" data-theme={selectedTheme}>
      <Header
        themes={themes}
        selectedTheme={selectedTheme}
        setSelectedTheme={setSelectedTheme}
      />
       </div>
    </>
  );
}
